from .base_rule import Rule, RegexRule, ASTRule, registry, register_rule
from .engine import RuleEngine
from . import rules  # built-in hand-written rules

# Import generated rules only if they exist
try:
    from . import generated_rules  # auto-generated by engine/utils/generate_rules.py
except ImportError:
    pass  # not yet generated — run: python -m engine.utils.generate_rules

__all__ = [
    "Rule",
    "RegexRule",
    "ASTRule",
    "registry",
    "register_rule",
    "RuleEngine",
]